version: "3"
services:
    consul:
      image: consul:1.7.1
      restart: always
      ports:
         - 8300:8300
         - 8301:8301
         - 8301:8301/udp
         - 8302:8302
         - 8302:8302/udp
         - 8400:8400
         - 8500:8500
      volumes:
        - /data/consul:/data/consul
      command: agent -server -data-dir=/data/consul -bootstrap -client=0.0.0.0 -ui